### ISSUE TITLE
reliability of the inversion results 

### ISSUE THREAD

**Issue by a18610910547** [HongjianFang/DSurfTomo#1]
How do you test the reliability of the inversion results of this program?. Do you have related methods or procedures? For example, the corresponding procedures to do the test board.

**Comment by HongjianFang** [comment]
Hi,
   You can check the reliability with the same criterions as for body waves. Checking the data fitting, synthetic tests and so on. The code is capable of doing synthetic tests, check the manual for details. 
   Hope it helps.

Hongjian Fang

**Comment by a18610910547** [comment]
Dear teacher：
      Thank you for your prompt reply. I've read your article (Direct inversion of surface wave dispersion for 3-D Shallow crustal structure based on ray tracing:Methodology and application). And I have used your program to carry out the surface wave inversion, and obtained the 3D shear wave velocity structure.
    Now，I want to do the test board experiment to test the reliability of the inversion results, but I don't know how to get the dispersion of the 3D theoretical model using forward calculation.
    Therefore, I want to require you the detailed steps of the test board experiment and what  the specific procedure of using it?
 
                                                                                                                           Yours  sincerely!

**Comment by HongjianFang** [comment]
I think I've mentioned that in the Manual, can you check the manual first.

Hongjian Fang

**Comment by a18610910547** [comment]
thank you teacher, I understand.

**Comment by Pulak-Biswas** [comment]
Can I do forward modeling for a synthetic model using DSurfTomo. If yes how can I do that.

**Comment by a18610910547** [comment]
Hello!
You can have a try.
Under the path: DsurfTomo/scripts, the theoretical model can be built by using the script Generate TrueMOD.py.




------------------ 原始邮件 ------------------
发件人: "PULAK1998"<notifications@github.com>;
发送时间: 2019年6月6日(星期四) 下午3:05
收件人: "HongjianFang/DSurfTomo"<DSurfTomo@noreply.github.com>;
抄送: "李选涛"<1694570173@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [HongjianFang/DSurfTomo] reliability of the inversion results (#1)




Can I do forward modeling for a synthetic model using DSurfTomo. If yes how can I do that.

**Comment by Pulak-Biswas** [comment]
Sir
      I actually want to produce phase velocity and group velocity
dispersion curve for a synthetic model by forward modeling. So can I do
that.

**Comment by a18610910547** [comment]
Sorry, I don't quite understand what you mean? Do you want to do resolution testing (checkerboard)?




------------------ 原始邮件 ------------------
发件人: "PULAK1998"<notifications@github.com>;
发送时间: 2019年6月6日(星期四) 下午5:19
收件人: "HongjianFang/DSurfTomo"<DSurfTomo@noreply.github.com>;
抄送: "李选涛"<1694570173@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [HongjianFang/DSurfTomo] reliability of the inversion results (#1)



Sir
       I actually want to produce phase velocity and group velocity
 dispersion curve for a synthetic model by forward modeling. So can I do
 that.

**Comment by PULAK1998** [comment]
I want to produce shear wave profiles by giving layer parameters i.e.,
thickness,vp, vs, and density for a layered model. Is it possible to get
those theoritical profiles?

**Comment by PULAK1998** [comment]
I want to produce shear wave profiles by giving layer parameters i.e.,
thickness,vp, vs, and density for a layered model. Is it possible to get
those theoritical profiles?

**Comment by nonpad** [comment]
Dear @a18610910547 
I just found the same confusion as you did which is about test the reliability of the inversion results. If this not bothering you, could you please help me to tell me the detailed steps of the test board and the specific procedure of using it? I already read the manual but still confused. Thanks in advance.

**Comment by a18610910547** [comment]
The 2D detection board can be made according to the program manual, while for the 3D detection board, the inverted layer thickness needs to be designed to be larger, for example, the inversion depth is 0-1km. Perhaps dividing the strata into three layers would suffice. The other steps are the same as 2D detection board testing


李选涛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HongjianFang/DSurfTomo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月14日(星期三) 晚上10:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HongjianFang/DSurfTomo] reliability of the inversion results  (#1)





 
Dear @a18610910547
 I just found the same confusion as you did which is about test the reliability of the inversion results. If this not bothering you, could you please help me to tell me the detailed steps of the test board and the specific procedure of using it? I already read the manual but still confused. Thanks in advance.
