### ISSUE TITLE
Fortran runtime error: Index '23' of dimension 2 of array 'scxf' above upper bound of 22

### ISSUE THREAD

**Issue by Aki-halas** [HongjianFang/DSurfTomo#10]
Hello, I got the following error when I ran the program：
[root@Z textXD]# ../src/DSurfTomo DSurfTomo.in  

                              DSurfTomo (v1.3)
 PLEASE contact Hongjain Fang (fanghj@mail.ustc.edu.cn) if you find any bug

 model origin:latitude,longitue
   28.2215  102.5475
 grid spacing:latitude,longitue
    0.0005    0.0005
 model dimension:nx,ny,nz
   10   10    9
 Rayleigh wave phase velocity used,periods:(s)
    0.0    0.1    0.1    0.1    0.1    0.1    0.1    0.1    0.1    0.1    0.1    0.1    0.2    0.2    0.2    0.2    0.2    0.2    0.2    0.2    0.2    0.2
At line 255 of file main.f90
Fortran runtime error: Index '23' of dimension 2 of array 'scxf' above upper bound of 22
About the period I set in DSurfTomo.in：0.04 0.05 0.06 0.07 0.08 0.09 0.10 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.20 0.21 0.22 0.23 0.24 0.25
I really hope to get your help, thank you very much.

**Comment by HongjianFang** [comment]
Hi, 
You may need to increase the source number parameter in your input file (the 8th line) to at least, or larger than, the number of your stations.

Cheers,
Hongjian Fang

**Comment by Aki-halas** [comment]
Thanks, this error has been resolved.But it seems that a new error has been encountered.I can make sure that both the source and receiver are within the scope of the set model, so I don't know why the error is being reported.Then, it seems that the period and depth parameters can only be read to one decimal place, can this be changed？
[root@Z textXD]# ../src/DSurfTomo DSurfTomo.in  

                              DSurfTomo (v1.3)
 PLEASE contact Hongjain Fang (fanghj@mail.ustc.edu.cn) if you find any bug

 model origin:latitude,longitue
   28.2281  102.5437
 grid spacing:latitude,longitue
    0.0010    0.0010
 model dimension:nx,ny,nz
   10   10    9
 Rayleigh wave group velocity used,periods:(s)
    0.0    0.1    0.1    0.1    0.1    0.1    0.1    0.1    0.1    0.1    0.1    0.1    0.2    0.2    0.2    0.2    0.2    0.2    0.2    0.2    0.2    0.2
Number of all measurements     14
 grid points in depth direction:(km)
    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
 computing sensitivity matrix...
 Source lies outside bounds of model (lat,long)=    90.0000000       0.00000000    
 TERMINATING PROGRAM!!!

**Comment by HongjianFang** [comment]
I have not tested the program for very small scales. The problem seems to do with the origin point you set.

**Comment by Bazzi26** [comment]
> Thanks, this error has been resolved.But it seems that a new error has been encountered.I can make sure that both the source and receiver are within the scope of the set model, so I don't know why the error is being reported.Then, it seems that the period and depth parameters can only be read to one decimal place, can this be changed？ [root@Z textXD]# ../src/DSurfTomo DSurfTomo.in
> 
> ```
>                           DSurfTomo (v1.3)
> ```
> 
> PLEASE contact Hongjain Fang ([fanghj@mail.ustc.edu.cn](mailto:fanghj@mail.ustc.edu.cn)) if you find any bug
> 
> model origin:latitude,longitue 28.2281 102.5437 grid spacing:latitude,longitue 0.0010 0.0010 model dimension:nx,ny,nz 10 10 9 Rayleigh wave group velocity used,periods:(s) 0.0 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 Number of all measurements 14 grid points in depth direction:(km) 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 computing sensitivity matrix... Source lies outside bounds of model (lat,long)= 90.0000000 0.00000000 TERMINATING PROGRAM!!!

Hi, have you solve the error?

**Comment by HongjianFang** [comment]
It looks like sth wrong with your data format. I would check it first and then the parameters in the input file.

**Comment by Bazzi26** [comment]
> It looks like sth wrong with your data format. I would check it first and then the parameters in the input file.

Thanks，I‘ll check it again.

**Comment by NingtanZhou** [comment]
Hello, I've got this problem:
I  have changed the staion number in  8th line  to make srue it's larger than actual station number.

(base) lily@lily:~/Tomo/DSurfTomo/testbox2$ ../bin/DSurfTomo DSurfTomo.in

                              DSurfTomo (v1.4)
 For bug report, PLEASE contact Hongjain Fang (fanghj1990@gmail.com)

 model origin:latitude,longitue
  26.60000  97.80000
 grid spacing:latitude,longitue
   0.20000   0.20000
 model dimension:nx,ny,nz
   16   16    5
 Rayleigh wave phase velocity used,periods:(s)
   0.50   0.60   0.70   0.80
At line 260 of file main.f90
Fortran runtime error: Index '46' of dimension 2 of array 'scxf' above upper bound of 4

Error termination. Backtrace:
#0  0x7f1da04acd11 in ???
#1  0x7f1da04ad859 in ???
#2  0x7f1da04aded6 in ???
#3  0x555e037d87e2 in ???
#4  0x555e037df18b in ???
#5  0x7f1da012d082 in __libc_start_main
	at ../csu/libc-start.c:308
#6  0x555e037ad2fd in ???
#7  0xffffffffffffffff in ???
As a postgraduate student, I would be very appreciative if I could get your help.
Thank you!

**Comment by NingtanZhou** [comment]
Hello, I've got this problem:
The format of stationlist.dat is the same as in your example.
                              DSurfTomo (v1.4)
 For bug report, PLEASE contact Hongjain Fang (fanghj1990@gmail.com)

 model origin:latitude,longitue
  26.60000  97.80000
 grid spacing:latitude,longitue
   0.02000   0.02000
 model dimension:nx,ny,nz
   16   16    5
 Rayleigh wave phase velocity used,periods:(s)
   0.50   0.60   0.70   0.80   0.90   1.00   1.10   1.20   1.30   1.40   1.50   1.60   1.70   1.80   1.90   2.00   2.10   2.20   2.30   2.40   2.50   2.60   2.70   2.80   2.90   3.00   0.00
At line 208 of file main.f90 (unit = 10, file = 'DSurfTomo.in')
Fortran runtime error: Bad integer for item 1 in list input

Error termination. Backtrace:
#0  0x7f81f34b6d11 in ???
#1  0x7f81f34b7859 in ???
#2  0x7f81f34b853f in ???
#3  0x7f81f36f1ef3 in ???
#4  0x7f81f36f5179 in ???
#5  0x7f81f36f5db9 in ???
#6  0x564501c7968e in ???
#7  0x564501c8118b in ???
#8  0x7f81f3137082 in __libc_start_main
	at ../csu/libc-start.c:308
#9  0x564501c4f2fd in ???
#10  0xffffffffffffffff in ???
As a postgraduate student, I would be very appreciative if I could get your help.
Thank you!

**Comment by AoChang56** [comment]
> Hello, I got the following error when I ran the program： [root@Z textXD]# ../src/DSurfTomo DSurfTomo.in
> 
> ```
>                           DSurfTomo (v1.3)
> ```
> 
> PLEASE contact Hongjain Fang ([fanghj@mail.ustc.edu.cn](mailto:fanghj@mail.ustc.edu.cn)) if you find any bug
> 
> model origin:latitude,longitue 28.2215 102.5475 grid spacing:latitude,longitue 0.0005 0.0005 model dimension:nx,ny,nz 10 10 9 Rayleigh wave phase velocity used,periods:(s) 0.0 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 At line 255 of file main.f90 Fortran runtime error: Index '23' of dimension 2 of array 'scxf' above upper bound of 22 About the period I set in DSurfTomo.in：0.04 0.05 0.06 0.07 0.08 0.09 0.10 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.20 0.21 0.22 0.23 0.24 0.25 I really hope to get your help, thank you very much.



> Hello, I got the following error when I ran the program： [root@Z textXD]# ../src/DSurfTomo DSurfTomo.in
> 
> ```
>                           DSurfTomo (v1.3)
> ```
> 
> PLEASE contact Hongjain Fang ([fanghj@mail.ustc.edu.cn](mailto:fanghj@mail.ustc.edu.cn)) if you find any bug
> 
> model origin:latitude,longitue 28.2215 102.5475 grid spacing:latitude,longitue 0.0005 0.0005 model dimension:nx,ny,nz 10 10 9 Rayleigh wave phase velocity used,periods:(s) 0.0 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 At line 255 of file main.f90 Fortran runtime error: Index '23' of dimension 2 of array 'scxf' above upper bound of 22 About the period I set in DSurfTomo.in：0.04 0.05 0.06 0.07 0.08 0.09 0.10 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.20 0.21 0.22 0.23 0.24 0.25 I really hope to get your help, thank you very much.

Hi, I met the same issue as you, do you remember how to fix it up??
