### ISSUE TITLE
请求可以生成不同周期台站间射线路径Raypath.out的DSurfTomo早期版本

### ISSUE THREAD

**Issue by Eanire** [HongjianFang/DSurfTomo#11]
尊敬的方博士您好，非常荣幸可以使用您的DSurfTomo程序。目前希望可以使用到DSurfTomo中生成各周期台站间射线路径的生成文件，在地震学学术年会上听闻早期版本可以实现，特向您请求下载DSurfTomo可以生成Raypath.out版本的文件包。
还想请问您Rayleigh波不同周期的深度敏感核是用什么程序做的呢？如果方便的话您可以做个分享吗？

**Comment by HongjianFang** [comment]
您好。射线路径输出可以用Rawlinson教授的FMST。DSurfTomo的话可以用命令git checkout v1.2（或者去https://github.com/HongjianFang/DSurfTomo/tags 直接下载1.2版本），重新编译运行后可以输出raypath.out。敏感核可以参考http://ciei.colorado.edu/Products/。

方洪健

**Comment by Eanire** [comment]
十分感谢您的回信和帮助。
祝您工作顺利，身体健康，万事如意。



---原始邮件---
发件人: "Hongjian ***@***.***&gt;
发送时间: 2024年3月15日(周五) 晚上6:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HongjianFang/DSurfTomo] 请求可以生成不同周期台站间射线路径Raypath.out的DSurfTomo早期版本 (Issue #11)




 
您好。射线路径输出可以用Rawlinson教授的FMST。DSurfTomo的话可以用命令git checkout v1.2（或者去https://github.com/HongjianFang/DSurfTomo/tags 直接下载1.2版本），重新编译运行后可以输出raypath.out。敏感核可以参考http://ciei.colorado.edu/Products/。
 
方洪健
