### ISSUE TITLE
Vertical checkerboard test

### ISSUE THREAD

**Issue by unanajee** [HongjianFang/DSurfTomo#12]
Hello Hongjian Fang

I am using DSurfTomo to invert 16870 dispersion measurements. I have done synthetics for horizontal layers and it's well resolved. Now I want to do a vertical checkerboard test for the same data. How I can achieve it. Please, Can you explain in detail how to produce a vertical checkerboard test.  I have also gone through your publication.  

Thank you

**Comment by HongjianFang** [comment]
Hi,
   It is possible to generate checkerboard model in the vertical direction with the simple python script 'generateTrueMod.py', just revise the line 'z=np.ones(nz)' to oscillating ones and negative ones. But I would not try too complex patterns as it would be difficult for surface wave to resolve them. Hope this helps.

Hongjian Fang

**Comment by unanajee** [comment]
Thank you
