### ISSUE TITLE
Fortran runtime error: Bad integer for item 1 in list input

### ISSUE THREAD

**Issue by NingtanZhou** [HongjianFang/DSurfTomo#13]
Hello, I've got this problem:
The format of stationlist.dat is the same as in your example.
DSurfTomo (v1.4)
For bug report, PLEASE contact Hongjain Fang ([fanghj1990@gmail.com](mailto:fanghj1990@gmail.com))

model origin:latitude,longitue
26.60000 97.80000
grid spacing:latitude,longitue
0.02000 0.02000
model dimension:nx,ny,nz
16 16 5
Rayleigh wave phase velocity used,periods:(s)
0.50 0.60 0.70 0.80 0.90 1.00 1.10 1.20 1.30 1.40 1.50 1.60 1.70 1.80 1.90 2.00 2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 0.00
At line 208 of file main.f90 (unit = 10, file = 'DSurfTomo.in')
Fortran runtime error: Bad integer for item 1 in list input

Error termination. Backtrace:
#0 0x7f81f34b6d11 in ???
https://github.com/HongjianFang/DSurfTomo/issues/1 0x7f81f34b7859 in ???
https://github.com/HongjianFang/DSurfTomo/pull/2 0x7f81f34b853f in ???
https://github.com/HongjianFang/DSurfTomo/pull/3 0x7f81f36f1ef3 in ???
https://github.com/HongjianFang/DSurfTomo/pull/4 0x7f81f36f5179 in ???
https://github.com/HongjianFang/DSurfTomo/issues/5 0x7f81f36f5db9 in ???
https://github.com/HongjianFang/DSurfTomo/issues/6 0x564501c7968e in ???
https://github.com/HongjianFang/DSurfTomo/issues/7 0x564501c8118b in ???
https://github.com/HongjianFang/DSurfTomo/issues/8 0x7f81f3137082 in __libc_start_main
at ../csu/libc-start.c:308
https://github.com/HongjianFang/DSurfTomo/issues/9 0x564501c4f2fd in ???
https://github.com/HongjianFang/DSurfTomo/issues/10 0xffffffffffffffff in ???
As a postgraduate student, I would be very appreciative if I could get your help.
Thank you!

**Comment by HongjianFang** [comment]
It looks like the number of periods is incorrect. I would check the data first.

Hongjian Fang

**Comment by NingtanZhou** [comment]
> It looks like the number of periods is incorrect. I would check the data first.
> 
> Hongjian Fang

It works,thank you! I have changed the periods in DSurfTomo.in , and now this problem have been solved.
However ,there are some new problems:
                              DSurfTomo (v1.4)
 For bug report, PLEASE contact Hongjain Fang (fanghj1990@gmail.com)

 model origin:latitude,longitue
  27.00000  96.00000
 grid spacing:latitude,longitue
   0.25000   0.25000
 model dimension:nx,ny,nz
   14   14    5
 Rayleigh wave phase velocity used,periods:(s)
   5.00   6.00   7.00   8.00   9.00  10.00  11.00  12.00  13.00  14.00  15.00  16.00  17.00  18.00  19.00  20.00  21.00  22.00  23.00  24.00  25.00  26.00  27.00  28.00  29.00  30.00  31.00  32.00  33.00  34.00  35.00  36.00  37.00  38.00  39.00  40.00
 Number of all measurements    690
 grid points in depth direction:(km)
   0.00   2.50   5.00   7.50  10.00
 computing sensitivity matrix...
 Rayleigh wave phase velocity depth kernel
 Source lies outside bounds of model (lat,long)=    90.0000000       0.00000000    
 TERMINATING PROGRAM!!!
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG

As linked above,
1:I checked my Stationlist.dat and found that all latitudes and longitudes are within the range of (22-27, 97-101). Does this indicate a problem with my data file or Initial model ?
2:Can I ignore the Note? This note seems to be a result but not the reason. 

Thank you for your patient reply.

**Comment by MrYuKunPeng** [comment]
I have also encountered the same problem as mentioned previously, and I would humbly seek your guidance on how to resolve it. 

                              DSurfTomo (v1.3)
 For bug report, PLEASE contact Hongjain Fang (fanghj1990@gmail.com)

 model origin:latitude,longitue
  38.05000 116.95000
 grid spacing:latitude,longitue
   0.05000   0.05000
 model dimension:nx,ny,nz
   75   85   21
 Rayleigh wave phase velocity used,periods:(s)
   1.00   1.50   2.00   2.50   3.00   3.50   4.00   4.50   5.00   5.50   6.00   6.50   7.00   7.50   8.00   8.50   9.00   9.50  10.00  10.50  1               1.00  11.50  12.00  12.50  13.00  13.50  14.00  14.50  15.00  15.50  16.00  16.50  17.00  17.50  18.00  18.50  19.00  19.50  20.00  20.50  21.0               0  21.50  22.00  22.50  23.00  23.50  24.00  24.50  25.00  25.50
  26.00  26.50  27.00  27.50  28.00  28.50  29.00  29.50  30.00
 Number of all measurements  73892
 grid points in depth direction:(km)
   0.00   0.20   0.60   1.20   2.00   3.00   4.20   5.60   7.20   9.00  11.00  13.20  15.60  18.20  21.00  24.00  27.20  30.60  34.20  38.00  4               2.00
 Synthetic Test Begin
 computing sensitivity matrix...
 Rayleigh wave phase velocity depth kernel
 Source lies outside bounds of model (lat,long)=    90.0000000       1.44473872E-42
 TERMINATING PROGRAM!!!
*** Error in `../src/DSurfTomo': munmap_chunk(): invalid pointer: 0x0000000001a82620 ***
Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
I would be deeply appreciative if I could receive your response.

**Comment by HongjianFang** [comment]
It looks like the problem is related to memory overflow. I would first try to reduce the number of model dimensions: nx, ny, and the number of dispersion measurements, for example, using an interval of 1 second or more instead of 0.5 seconds. Hope this helps.

Hongjian Fang

**Comment by MrYuKunPeng** [comment]
Thank you very much for your reply. The issue has been resolved.
