### ISSUE TITLE
 mean,std_devs and rms of residual after weighting:      0.0ms     0.00ms    0.000  min and max velocity variation  0.0000 0.0000

### ISSUE THREAD

**Issue by NingtanZhou** [HongjianFang/DSurfTomo#14]
Hello!
After solving the problem in the last email, the program works, but it seems that my data is not involved in the inversion? Looking forward to hearing from you!

                              DSurfTomo (v1.4)

 For bug report, PLEASE contact Hongjain Fang ([fanghj1990@gmail.com](mailto:fanghj1990@gmail.com))

 model origin:latitude,longitue
  27.00000  96.00000
 grid spacing:latitude,longitue
   0.50000   0.50000
 model dimension:nx,ny,nz
   14   14    4
 Rayleigh wave phase velocity used,periods:(s)
   5.00   6.00   7.00   8.00   9.00  10.00  11.00  12.00  13.00  14.00  15.00  16.00  17.00  18.00  19.00  20.00  21.00  22.00  23.00  24.00  25.00  26.00  27.00  28.00  29.00  30.00  31.00  32.00  33.00  34.00  35.00
 Number of all measurements    690
 grid points in depth direction:(km)
   0.00   2.50   5.00   7.50
 computing sensitivity matrix...
 Rayleigh wave phase velocity depth kernel
 1th iteration...
 mean,std_devs and rms of residual after weighting:      0.0ms     0.00ms    0.000
 min and max velocity variation  0.0000 0.0000
 computing sensitivity matrix...
 Rayleigh wave phase velocity depth kernel
 2th iteration...
 mean,std_devs and rms of residual after weighting:      0.0ms     0.00ms    0.000
 min and max velocity variation  0.0000 0.0000
 computing sensitivity matrix...
 Rayleigh wave phase velocity depth kernel
 3th iteration...
 mean,std_devs and rms of residual after weighting:      0.0ms     0.00ms    0.000
 min and max velocity variation  0.0000 0.0000
 computing sensitivity matrix...
 Rayleigh wave phase velocity depth kernel
 4th iteration...
 mean,std_devs and rms of residual after weighting:      0.0ms     0.00ms    0.000
 min and max velocity variation  0.0000 0.0000
 computing sensitivity matrix...
 Rayleigh wave phase velocity depth kernel
 5th iteration...
 mean,std_devs and rms of residual after weighting:      0.0ms     0.00ms    0.000
 min and max velocity variation  0.0000 0.0000
 computing sensitivity matrix...
 Rayleigh wave phase velocity depth kernel
 6th iteration...
 mean,std_devs and rms of residual after weighting:      0.0ms     0.00ms    0.000
 min and max velocity variation  0.0000 0.0000
 computing sensitivity matrix...
 Rayleigh wave phase velocity depth kernel
 7th iteration...
 mean,std_devs and rms of residual after weighting:      0.0ms     0.00ms    0.000
 min and max velocity variation  0.0000 0.0000
 computing sensitivity matrix...
 Rayleigh wave phase velocity depth kernel
 8th iteration...
 mean,std_devs and rms of residual after weighting:      0.0ms     0.00ms    0.000
 min and max velocity variation  0.0000 0.0000
 computing sensitivity matrix...
 Rayleigh wave phase velocity depth kernel
 9th iteration...
 mean,std_devs and rms of residual after weighting:      0.0ms     0.00ms    0.000
 min and max velocity variation  0.0000 0.0000
 computing sensitivity matrix...
 Rayleigh wave phase velocity depth kernel
10th iteration...
 mean,std_devs and rms of residual after weighting:      0.0ms     0.00ms    0.000
 min and max velocity variation  0.0000 0.0000
 Program finishes successfully
 Output inverted shear velocity model to DSurfTomo.inMeasure.dat

**Comment by NingtanZhou** [comment]
Whose problem is it? Parameter Settings, model, or data?

**Comment by NingtanZhou** [comment]
I wonder if this is something wrong with the model, the input parameters, or the data?Thank you!

**Comment by HongjianFang** [comment]
I would refer to some depth kernels before trying random grids in the depth direction. For example, surface waves with periods larger than 30 seconds would be sensitive to ~50 km. Your depth grids are far too shallow. Hope this helps.

Hongjian Fang

**Comment by HongjianFang** [comment]
I would refer to some depth kernels before trying random grids in the depth direction. For example, surface waves with periods larger than 30 seconds would be sensitive to ~50 km. Your depth grids are far too shallow. Hope this helps.

Hongjian Fang

**Comment by NingtanZhou** [comment]
> I would refer to some depth kernels before trying random grids in the depth direction. For example, surface waves with periods larger than 30 seconds would be sensitive to ~50 km. Your depth grids are far too shallow. Hope this helps.
> 
> Hongjian Fang

Thank you!!! I doubted that,this reply helps a lot!
