### ISSUE TITLE
Fortran runtime error: Index '42' of dimension 2 of array 'scxf' above upper bound of 41

### ISSUE THREAD

**Issue by Stuxuk** [HongjianFang/DSurfTomo#17]
Dear Dr. Fang, I encountered this error when using DSurfTomo. At first, I guessed that the mesh parameters did not correspond, but after checking, I still reported an error.What is the probable reason? Thank you very much

DSurfTomo (v1.3)
 PLEASE contact Hongjain Fang (fanghj@mail.ustc.edu.cn) if you find any bug

 input file [DSurfTomo.in(default)]:
./DSurfTomo.in
 model origin:latitude,longitue
   30.5800  112.9310
 grid spacing:latitude,longitue
    0.5000    0.5000
 model dimension:nx,ny,nz
   30   30   12
 Rayleigh wave phase velocity used,periods:(s)
    5.0    6.0    7.0    8.0    9.0   10.0   11.0   12.0   13.0   14.0   15.0   16.0   17.0   18.0   19.0   20.0   21.0   22.0   23.0   24.0   25.0   26.0   27.0   28.0   29.0   30.0   31.0   32.0   33.0   34.0   35.0   36.0   37.0   38.0   39.0   40.0   41.0   42.0   43.0   44.0   45.0
At line 255 of file main.f90
Fortran runtime error: Index '42' of dimension 2 of array 'scxf' above upper bound of 41

Error termination. Backtrace:
#0  0x7afe8781b31a
#1  0x7afe8781bec5
#2  0x7afe8781c297
#3  0x5db04c40b269
#4  0x5db04c40141e
#5  0x7afe87429d8f
#6  0x7afe87429e3f
#7  0x5db04c401459
#8  0xffffffffffffffff

**Comment by HongjianFang** [comment]
Hi, 
   The 'nsrcs' parameter in the input file should be at least as large as your number of stations.

**Comment by Stuxuk** [comment]
Thank you for your patient reply. I have solved the problem!
