### ISSUE TITLE
Data syntetic

### ISSUE THREAD

**Issue by nonpad** [HongjianFang/DSurfTomo#18]
Dear Dr. Fang,
I want to do the resolution test (checkerboard) I have already run the GenerateTrueMOD and obtained the MOD.true file. However, I am a bit confused about where to find the synthetic data from forward modeling for the inversion process. Is the data in MOD.true considered synthetic data? If so, how should I format it to match the format of the surfdata.dat file required for the inversion? Thanks in advance.

**Comment by HongjianFang** [comment]
Hi there,
  The program does not output synthetic data. It does synthetic test automatically once you provided MOD.true and set the synthetic flag in the input file to 1. You can refer to the manual for more details. Hope this helps.

Cheers,
Hongjian Fang

**Comment by nonpad** [comment]
Dear Dr. Fang,
Sorry that I am still confused with the checkerboard test,
If I am not mistake, when we set the synthetic flag to 1 is the input data for data file still same as the data file when we use real data which is 'surfdata.dat'?
And then, after we run the program, the output we get are true velocity model, inverted shear velocity model, and velmap2dRg. 
My question is which file is the recovered checkerboard patterns? Thanks in advance.

**Comment by HongjianFang** [comment]
Hi,
   Sorry for the confusion. Yes, the input data is the same. For synthetic data, you also need to provide a model file named 'MOD.true'. Then the program will use the same source and receiver distribution for generating dispersion data. For the output files, the program also output the true model, which is the same as 'MOD.true' but is reformatted for GMT plotting. The other files are the same as field data. Let me know if you have further question.

Hongjian Fang
