### ISSUE TITLE
checkerboard recovery

### ISSUE THREAD

**Issue by blackpanda1121** [HongjianFang/DSurfTomo#20]
Dear Dr. Fang.

I have a question about the TrueMOD or the checkerboard. How do you plot the checkerboard recovery in DSurfTomo? Also what is the unit of the axis when you generate the TrueMOD, i got confused because it only tell the number of nx, ny, nz that I input, not the unit information. 

Thank you in advance Dr. Fang.

**Comment by HongjianFang** [comment]
Hi there,
   After setting the 'synthetic' parameter to 1 and finishing running the code, there should be an output file that contains the true velocity model and with the same format as the inverted model, therefore you can plot them with the GMT script I provided or whatever ways you like. 
  The units are the same as the 'dvxd,dvzd' parameter you specified in the input file. Hope this helps.

Hongjian Fang

**Comment by blackpanda1121** [comment]
The checkerboard recovery is clear, thank you. But I want to make sure about the units, if my input are in longitude/latitude and the dvxd,dvzd is 0.001, is it right that my grid are 0.1x0.1 km? assume that 1 long/lat equals to 111 km. Thank you in advance.
![messageImage_1725867667719](https://github.com/user-attachments/assets/927e9e28-49bb-477d-b09c-e4e02d05a87c)
