### ISSUE TITLE
The grids on the model edges are vaild or not?

### ISSUE THREAD

**Issue by MistBornPow** [HongjianFang/DSurfTomo#22]
Dear Dr. Fang,

Since my input model size is 32x32 and the output model is 30x30. Does that mean we have to exclude the edge of the model?
Is this issue related to the calulation of FMM? I'm not quite sure about that. I notice that FMST package also exclude the model boundary at plotting step.

_Originally posted by @MistBornPow in https://github.com/HongjianFang/DSurfTomo/issues/19#issuecomment-2342956037_

**Comment by HongjianFang** [comment]
Hi,
  Yes, we excluded the boundary points when outputting the inverted model. Hope this helps.

Hongjian Fang
