### ISSUE TITLE
checkerboard recovery (2)

### ISSUE THREAD

**Issue by blackpanda1121** [HongjianFang/DSurfTomo#23]
Dear Mr. Fang.

When i ran the synthetic data using MOD.true, there is several output that generated. I am confused about the difference between "DSurfTomo.inSyn" and "Vs_model.real". Which one is the right output for checkerboard recovery? Thank you in advance and sorry for asking so much question lately.

**Comment by HongjianFang** [comment]
Hi,
   As the names suggested, the 'real' is the input model, the 'Syn' is the obtained model. You can plot both of them out and then it will be clear which is which. Hope this helps.

Hongjian Fang

**Comment by blackpanda1121** [comment]
Thank you for your answer Mr. Fang
