### ISSUE TITLE
代码使用垂询

### ISSUE THREAD

**Issue by LevCarlo** [HongjianFang/DSurfTomo#5]
代码使用过程中出现如下问题：
`error with allocate: integer iw`
`Program received signal SIGSEGV:Segmentation fault - invalid memory reference`

**Comment by HongjianFang** [comment]
Sorry for the delay. You should probably increase the parameter 'sparsity fraction'  in the input file.

**Comment by LevCarlo** [comment]
> Sorry for the delay. You should probably increase the parameter 'sparsity fraction' in the input file.
Thank You

**Comment by LevCarlo** [comment]
> Sorry for the delay. You should probably increase the parameter 'sparsity fraction' in the input file.

Thank you
