### ISSUE TITLE
No 'raypath.out' in output files

### ISSUE THREAD

**Issue by MrXiaoXiao** [HongjianFang/DSurfTomo#8]
According to the manual, there should be a 'raypath.out' file after inversion. 

"""
The raypath distribution of the final model (raypath.out) # 
number of ray path segments 
latitude longitude 
"""

However, I didn't find this file in the outputs. I also checked DSurfTomo source codes and didn't find the codes to write ray path geometries either. So, how can I save and plot ray paths?

**Comment by HongjianFang** [comment]
Hi, I've removed the function of outputing raypath since I don't find it very helpful. You can go back to V1.2 if you still want to plot the raypaths at different periods.

Hope this helps,
Hongjian

**Comment by MrXiaoXiao** [comment]
OK! Thank you.
