### ISSUE TITLE
Unable to open the input file

### ISSUE THREAD

**Issue by chinu739** [HongjianFang/DSurfTomo#9]
I used the command as mentioned in the manual "./src/DSurfTomo DSurfTomo.in" , somehow it shows this " DSurfTomo (v2.0)
 For bug report, PLEASE contact Hongjain Fang (fanghj1990@gmail.com)

STOP unable to open the inputfile"
would be grateful for fixing this issue. Thank you

**Comment by HongjianFang** [comment]
Hi,
   I wonder which directory did you run the command? You should run it in the directory where you have your input data and input file ready. 

Cheers,
Hongjian Fang

**Comment by HongjianFang** [comment]
Hi,
   I wonder which directory did you run the command? You should run it in the directory where you have your input data and input file ready. 

Cheers,
Hongjian Fang
